### ISSUE TITLE
AOD with CHS bug

### ISSUE THREAD

**Issue by jjbuchanan** [cms-jet/JetToolbox#26]
If one is using AOD with the CHS pileup method, jetToolbox_cff.py will not be able to assign a value to srcForPFJets before attempting to use it in line 235, resulting in a fatal error. This is due to the "if" statement on line 226 having no corresponding "else". Is the "if" statement on line 226 even necessary?

**Comment by alefisico** [comment]
Hi @jjbuchanan thanks for point this out. I will try to fix this issue as soon as possible.

**Comment by alefisico** [comment]
Hi again @jjbuchanan I think I fixed it. You can see it here:
https://github.com/cms-jet/JetToolbox/blob/jetToolbox_74X/python/jetToolbox_cff.py#L233-L247
I am not sure if you are trying to create a new PFCollection or not, but the problem was introduced once I was adding this functionality. If this is the case, or even if is not, could you please test it and let me know if the problem persists? Notice that the fix is still not in the main branch but in the jetToolbox_74X.
cheers,

**Comment by jjbuchanan** [comment]
Thanks for the quick update. It seems to be functioning now. I'll keep you posted if I notice any further issues.
